version: "3.8"

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    labels:
      prometheus.io/scrape: "true"
      prometheus.io/port: 9100
    ports:
    - 9100:9100

  filesd:
    image: "acamilleri/prometheus-aio-filesd:latest"
    container_name: filesd
    environment:
      FILESD_PROVIDER_NAME: "docker"
      FILESD_WRITER_NAME: "file"
      FILESD_WRITER_FILE_DEST: "/filesd/docker.json"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - filesd:/filesd
    labels:
      prometheus.io/scrape: "false"
    depends_on:
    - prometheus
    - node_exporter

  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    labels:
      prometheus.io/scrape: "true"
      prometheus.io/port: 9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - filesd:/etc/prometheus/filesd
    ports:
    - 9090:9090

volumes:
  file_sd:
